### ISSUE TITLE
Persistent MQ

### ISSUE THREAD

**Issue by gedw99** [Xe/olin#6]
I think liftbridge would be a good match.
It's NATS with persistence with a Kafka like log system.

https://github.com/liftbridge-io/liftbridge

If you know NATS you know the performance and scalability is great.
But NATS does not have persistence or security ( multi-purpose the ).
Liftbridge adds both and Kafka semantics.

The API for publishers is relies on NATS import..
For subs rivers is just grpc / golang because they don't need to know NATS is behind it.
The db is cockroach db or boltdb. 
So very few dependencies.

**Comment by Mec-iS** [comment]
My two cents: considering the initial example made about `libc`, I would consider Redis as a memory management system. Also Redis modules system provides the possibility of creating extensions in plain C.

**Comment by gedw99** [comment]
my 2 cents. I dont want any c code to be dependent on.

**Comment by Mec-iS** [comment]
> where is the libc dependency in the current code

I wrote "in the example" (in your blog). You took as example a dagger "serving" (is this the right word?) `libc`

Then you should probably provide your own stack/pub-sub implementation, may be with a proper dagger.

**Comment by gedw99** [comment]
Thanks. Makes sense.
I will proceed as you suggested to provider a Dagger based on NATS pub sub.

But ithe existing code would need some refactoring to have a driver interface etc so that both the c driver and the NATS driver can coexist. 
Is that inline with you ?

**Comment by Mec-iS** [comment]
What I can say with the current limited information about this nice project is:
1. You may want to start from an higher level of the stack, choosing the right generic tools and then slowly lower the bounds to provide language/compiler agnosticism
2. as far as I understood you want to focus on interfaces/processes; so you want to have pluggable components to handle the other functions of the stack (mostly brokerage function). But you may want to consider a more general purpose tool to free you from some hassle and focus on interfaces, then Redis is more portable and also meant to be used on low-memory devices (it works down to 16Mb of RAM afaik); plus it is flexible enough to be used as broker, queue, generic interface to memory with safest possible C subroutines, it can store binaries and has a dedicated sub-system to create your own modules in pure C. There is plenty of documentation about creating basic data structure with Redis.
3. You probably want a well rooted and extendable API/ABI documentation framework, I can help with that.

**Comment by Xe** [comment]
To be completely honest, I have avoided making any technology choices in this regard because I don't think that the bikeshed discussion is worth it _yet_ (personally I've been looking at [Kafka](https://kafka.apache.org/) and [Sandglass](https://github.com/sandglass/sandglass), but I'm avoiding releasing any code of it integrating with those YET). I want to have this use some kind of durable message queue. I would like consumer groups to be supported by this queue somehow, such that we can have multiple handlers for the same event type. [Redis streams](https://redis.io/topics/streams-intro) may also be an option, but this really boils down to an implementation detail, which is not what I want to really spend my time and energy focusing on _yet_.

Again, to avoid the illusion of anything being set in stone, no hard technology choices have been made yet in regards to message queue tech. 

> You probably want a well rooted and extendable API/ABI documentation framework, I can help with that.

https://christine.website/blog/olin-2-the-future-09-5-2018 for the things I'm currently playing around with at an idea stage. I was gonna start implementing this later today.
